In [ ]:
數值
float
int
complex
布林值(bool)
文字(str)

回傳值type()



In [2]:
help(type)

Help on class type in module builtins:

class type(object)
 |  type(object_or_name, bases, dict)
 |  type(object) -> the object's type
 |  type(name, bases, dict) -> a new type
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __dir__(...)
 |      __dir__() -> list
 |      specialized __dir__ implementation for types
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __instancecheck__(...)
 |      __instancecheck__() -> bool
 |      check if an object is an instance
 |  
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __prepare__(...)
 |      __prepare__() -> dict
 |      used to create the namespace for the class statement
 |  
 

In [18]:
print(type(5)) 
print(type(5.5))
print(type(5 + 3j))#complex，python把虛數i叫做j
print(type(True))
print(type(False))
print(type("2017 ithome ironman"))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bool'>
<class 'str'>


In [25]:
print(1.0 == True)
print(0 == False)
print(1.2 + True)
print(3 + True * 2)
print("2017 ithom ironman" + "rocks!")
print("2017 ithom ironman" + "rocks"+ "!"*3)

True
True
2.2
5
2017 ithom ironmanrocks!
2017 ithom ironmanrocks!!!


In [27]:
days = 30
print("In order to become an ironman, you have to publish an article a day for " + days + " days in a row.")

TypeError: must be str, not int

In [39]:
days = 30
days += 3
print(days)
days -=3
print(days)
days *=5
print(days)
days /=3
print(days)
days %=7
print(days)

33
30
150
50.0
1.0


In [41]:
days = 30
print("In order to become an ironman, you have to publish an article a day for " + str(days) + " days in a row.")

In order to become an ironman, you have to publish an article a day for 30 days in a row.


In [43]:
my_bool = True
print(type(my_bool)) # 'bool'
print(float(my_bool)) # 1.0
print(int(my_bool)) # 1
print(complex(my_bool)) # 1+0j
print(type(str(my_bool))) # 'str'

<class 'bool'>
1.0
1
(1+0j)
<class 'str'>


# 方法一：客氣
ironman_group_1 = "Modern Web"
ironman_group_2 = "DevOps"
ironman_group_3 = "Cloud"
ironman_group_4 = "Big Data"
ironman_group_5 = "Security"
ironman_group_6 = "自我挑戰組"

# 方法二：善用
ironman_groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", 
"自我挑戰組"]

Python 基本的資料結構大致有三類：

list:Python 的 list 跟 R 語言的 list 相似，可以容納不同的變數類型與資料結構，
    雖然它的外觀長得跟 R 語言的 vector 比較像，但是他們之間有著截然不同的特性，
    那就是 R 語言的 vector 會將元素轉換成為同一變數類型，但是 list 不會。
tuple:tuple 跟 list 很像，但是我們不能新增，刪除或者更新 tuple 的元素，
    這樣的資料結構沒有辦法對應到 R 語言。
    我們可以使用 tuple() 函數將既有的 list 轉換成為 tuple，
    或者在建立物件的時候使用小括號 () 有別於建立 list 的時候使用的中括號 []。
dictionary: dictionary 是帶有鍵值（key）的 list，
    這樣的特性讓我們在使用中括號 [] 選擇元素時可以使用鍵值，
    在建立 Python 的 dictionary 時候我們只需要使用大括號 {} 或者使用 dict() 
    函數轉換既有的 list。

In [6]:
#list
participated_group = "Big Data"
current_ttl_articles = 4
is_participating = True

my_status = [participated_group, current_ttl_articles, is_participating]
print(my_status[0])
print(my_status[1])
print(my_status[2])

Big Data
4
True


In [8]:
# 分別建立 list 與 tuple
ironman_groups_list = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security"]
ironman_groups_tuple = tuple(ironman_groups_list)

# 新增一個元素
ironman_groups_list.insert(5, "自我挑戰組")
ironman_groups_tuple.insert(5, "自我挑戰組")

AttributeError: 'tuple' object has no attribute 'insert'

In [41]:
participated_group = "Big Data"
current_ttl_articles = 4
is_participating = True

# 建立 dictionary
my_status = {
    "group": participated_group,
    "ttl_articles": current_ttl_articles,
    "is_participating": is_participating
}

# 利用鍵值選擇元素
print(my_status["group"])
print(my_status["ttl_articles"])
print(my_status["is_participating"])

Big Data
4
True


In [11]:
ironmen = [46, 8, 11, 11, 4, 56]
articles = ironmen*30
print(articles)

[46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56, 46, 8, 11, 11, 4, 56]


In [13]:
ironmen = [46, 8, 11, 11, 4, 56]
article_multiplier = [30, 30, 30, 30, 30, 30]
articles = ironmen * article_multiplier
print(articles)

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
import numpy as np

iron = np.array([46,8,11,11,4,56])# 將 list 透過 numpy 的 array 方法進行轉換
print(iron)
print(type(iron))
articles = iron*30
print(articles)

[46  8 11 11  4 56]
<class 'numpy.ndarray'>
[1380  240  330  330  120 1680]


In [21]:
#單一資料類型
#NumPy 的 ndarray 只能容許一種資料類型，
#如果同時儲存有數值，布林值，會被自動轉換為數值，
#如果同時儲存有數值，布林值與文字，會被自動轉換為文字。

import numpy as np
my_np_array = np.array([1,True])
print(my_np_array.dtype)
my_np_array = np.array([1,True,"one"])
print(my_np_array.dtype)

int32
<U11


In [26]:
import numpy as np
my_2d_array = np.array([[1,True],
                      [0,False]])
print(my_2d_array)

my_2d_array = np.array([[1,True],
                        [0,"Zero"]])
print(my_2d_array)

[[1 1]
 [0 0]]
[['1' 'True']
 ['0' 'Zero']]


In [29]:
import numpy as np
my_array = np.array([[1,2],
                     [3,4]])
print(my_array**2)



[[ 1  4]
 [ 9 16]]


In [35]:
import numpy as np

iron = np.array([46,8,11,11,5,88])
print(iron[0])# 選出 Modern Web 組的鐵人數
print(iron>10)# 哪幾組的鐵人數超過 10 人
print(iron[iron>10])# 超過 10 人的鐵人數

46
[ True False  True  True False  True]
[46 11 11 88]


In [36]:
import numpy as np

ironmen_2d_array = np.array([[46, 11, 4],
                            [8, 11, 56]])
print(ironmen_2d_array[0, 0]) # 選出 Modern Web 組的鐵人數
print(ironmen_2d_array > 10) # 哪幾組的鐵人數超過 10 人
print(ironmen_2d_array[ironmen_2d_array > 10]) # 超過 10 人的鐵人數

46
[[ True  True False]
 [False  True  True]]
[46 11 11 56]


In [39]:
import numpy as np

iron = np.array([[14,12,18],
                 [58,8,95]])
print(iron.size)
print(iron.shape)

6
(2, 3)


In [44]:
import pandas as pd

groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
iron = [16,45,158,78,15,56]

iron_dic = {"groups":groups,
            "iron":iron
            }
iron_df = pd.DataFrame(iron_dic)

print(iron_df)
print(type(iron_df))


       groups  iron
0  Modern Web    16
1      DevOps    45
2       Cloud   158
3    Big Data    78
4    Security    15
5       自我挑戰組    56
<class 'pandas.core.frame.DataFrame'>


In [2]:
import pandas as pd
import numpy as np

my_2D_array = np.array([[1,2],
                        [3,4]])
my_df = pd.DataFrame(my_2D_array,columns = ["col1","col2"])

print(my_df)


   col1  col2
0     1     2
1     3     4


In [9]:
import pandas as pd

groups = ["Web","DevOps","cloud","Big Data","Security","自我挑戰組"]
irons = [46,5,8,41,58,4]

irons_dict = {"groups" : groups,
             "irons" : irons}
irons_df = pd.DataFrame(irons_dict)