我們在昨天的學習筆記討論了 Python 基本變數類型與資料結構可以應用的屬性或方法，除了基本的資料結構以外，你是否還記得 Python 可以透過引入 numpy 套件之後使用 ndarray 資料結構呢？當時我們在 [第 05 天] 資料結構（2）ndarray 提到，為了解決 Python 的 list 資料結構無法進行 element-wise 的運算，因此使用了 numpy 套件的 ndarray，我們勢必要瞭解她常見的屬性或方法。

numpy 與 ndarray 的常用屬性或方法

瞭解 ndarray 的概觀

ndim 屬性
shape 屬性
dtype 屬性

In [9]:
# 瞭解 ndarray 的概觀

# ndim 屬性
# shape 屬性
# dtype 屬性
import numpy as np

bb104 = [16,15,48,58,25,36]
bb104_array = np.array(bb104)

print(bb104_array.ndim)# number of dimensions
print(bb104_array.shape)# m*n
print(bb104_array.dtype)# 資料類型

# 2d array
bb105 = [[16,87,5,52,65,2],
         range(1,7)]
bb105_array = np.array(bb105)
print(bb105_array.ndim)
print(bb105_array.shape)
print(bb105_array.dtype)

1
(6,)
int32
2
(2, 6)
int32


In [1]:
# 建立 ndarray

# numpy 套件除了 array() 方法可以將 list 轉換成 ndarray，還有其他的方法可以建立 ndarray。

# zeros() 方法
# empty() 方法
# arange() 方法

import numpy as np
print(np.zeros(6)) # 6個元素均為零的 1d array
print("-----------------------")
print(np.zeros((2,6))) # 12個元素均為零的 2d array
print("-----------------------") # 二十四個元素均為未初始化的值
print(np.empty((2,6,2)))
print("-----------------------")
print(np.arange(11)) # 十一個元素為 0 到 10 的 1d array

[ 0.  0.  0.  0.  0.  0.]
-----------------------
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
-----------------------
[[[  6.23042070e-307   4.67296746e-307]
  [  1.69121096e-306   1.95819673e-306]
  [  1.33508845e-306   1.33511969e-306]
  [  6.23037996e-307   6.23053954e-307]
  [  9.34609790e-307   8.45593934e-307]
  [  9.34600963e-307   1.86921143e-306]]

 [[  6.23061763e-307   6.23053954e-307]
  [  2.22522597e-306   1.06810268e-306]
  [  6.23052935e-307   1.33512376e-306]
  [  1.20161118e-306   1.42418172e-306]
  [  1.37961641e-306   1.22383391e-307]
  [  8.45610231e-307   2.10081501e-312]]]
-----------------------
[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
#轉換變數類型
#ndarray 的 astype() 方法可以轉換變數類型。

import numpy as np
iron = ["58","84","5","63","14",]
iron_string_array = np.array(iron)

print(iron_string_array.dtype)
print("---------------")

#轉換為int64
iron_int_array = iron_string_array.astype(np.int64)
print(iron_int_array.dtype)

<U2
---------------
int64


用索引值進行篩選

利用 [] 搭配索引值篩選 ndarray，這點與 R 語言作法相同。

In [18]:
import numpy as np

my_array = np.arange(10)
print(my_array[0])
print(my_array[0:5])
print("---------------")

my_2d_array = np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print("------------")
print(my_2d_array[1,:])#第二列
print(my_2d_array[:,1])#第二行
print(my_2d_array[0,4])#第一列第五行

0
[0 1 2 3 4]
---------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
------------
[5 6 7 8 9]
[1 6]
4


布林值進行篩選

利用布林值（bool）篩選 ndarray。

In [23]:
import numpy as np

irons = [58,41,2,53,45]
groups = ["web","java","python","jdbc","html"]
iron_array = np.array(irons)
group_array = np.array(groups)
# 用人數去篩選組別
print(iron_array>=10)
print(group_array[iron_array>=10])

# 用組別去篩選人數
print(group_array!="html")
print(iron_array[group_array!="html"])#除了html以外的人數

[ True  True False  True  True]
['web' 'java' 'jdbc' 'html']
[ True  True  True  True False]
[58 41  2 53]


2d array 轉置

使用 T 屬性。

In [25]:
import numpy as np
my_1d_array = np.arange(10)
my_2d_array = my_1d_array.reshape((2,5))
print(my_2d_array)
print("----------")
print(my_2d_array.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
----------
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


numpy 的 where 方法

透過 numpy 的 where() 方法在 ndarray 中進行流程控制。

In [28]:
import numpy as np

iron_array = np.array([58,6,47,19,45,np.nan])
print(iron_array)
np.where(np.isnan(iron_array),71,iron_array)
#先把non值剔除，再加入71，在印出iron_array

[ 58.   6.  47.  19.  45.  nan]


array([ 58.,   6.,  47.,  19.,  45.,  71.])

排序

透過 sort() 方法。

In [29]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, 71])
print(ironmen_array)
ironmen_array.sort()
print(ironmen_array)

[56  8 19 14  6 71]
[ 6  8 14 19 56 71]


隨機變數

透過 numpy 的 random() 方法可以生成隨機變數。

In [34]:
import numpy as np

normal_samples = np.random.normal(size = 10)
uniform_samples = np.random.uniform(size = 10)

print(normal_samples)
print("---------")
print(uniform_samples)

[-0.13399817 -1.30211355  1.24088828 -1.96556139  0.33944173  1.14917717
 -0.65618036 -1.53172414  0.36949634  0.41421569]
---------
[ 0.20370097  0.08827768  0.77526483  0.38403757  0.86796225  0.53651484
  0.78787549  0.84263158  0.05138973  0.5960867 ]
