In [9]:
#array分割

import numpy as np

A = np.arange(12).reshape((3,4))

print(A)

print(np.split(A, 3, axis=0))#對橫向進行分割成三塊
print(np.array_split(A, 3, axis=1))#不等量分割

print(np.vsplit(A,3))         #對縱向分割
print(np.hsplit(A,2))         #對橫向分割


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [23]:
#array copy
import numpy as np
a = np.arange(4)
print(a)

b = a
c = a
d = b

a[0] = 11
print(a)
b is a

print(b)
print(d)

d[1:3]=[22,33]
print(d)
print(a)

b = a.copy() #deep copy 
print(b)
a[3] = 555555 #a的更動不會影響到b
print(a)
print(b)

[0 1 2 3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[       11        22        33 555555555]
[11 22 33  3]
