In [1]:
import numpy as np
array=np.array([[1,2,3],[2,3,4,]])
print(array)
print('number of dim:',array.ndim)
print('shap:',array.shape)
print('size:',array.size)



[[1 2 3]
 [2 3 4]]
number of dim: 2
shap: (2, 3)
size: 6


In [7]:
import numpy as np
a=np.array([2,23,4],dtype=np.float)
print(a.dtype)



float64


In [14]:
import numpy as np
a=np.array([[2,23,4],
            [2,32,5]])
b=np.zeros((3,4))
c=np.ones((3,4),dtype=np.int)
d=np.empty((3,4))

print(a)
print(b)
print(c)
print(d)

[[ 2 23  4]
 [ 2 32  5]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [23]:
import numpy as np

a=np.arange(10,20,2)
b=np.arange(0,40,2).reshape((5,4))

print(a)
print(b)

[10 12 14 16 18]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]


In [29]:
import numpy as np
a=np.linspace(1,10,6).reshape((2,3))
print(a)

[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]


In [38]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)
c=10*np.cos(a)
print(c)

[10 20 30 40] [0 1 2 3]
[-8.39071529  4.08082062  1.5425145  -6.66938062]


In [42]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(b)
print(b==3)

[0 1 2 3]
[False False False  True]


In [51]:
import numpy as np
a = np.array([[1,1],
              [0,1]])

b = np.arange(4).reshape((2,2))
print(a)
print(b)


c = a*b #逐個元素運算
c_dot = np.dot(a,b)#矩陣運算
c_dot_2 = a.dot(b)#意思就是說a跟b做矩陣運算
print(c)
print(c_dot)
print(c_dot_2)


[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [55]:
import numpy as np
a=np.random.random((2,4))
print(a)
print(np.sum(a,axis=1))
print(np.min(a,axis=0))
print(np.max(a,axis=1))



[[ 0.1257997   0.73621504  0.12380393  0.69277979]
 [ 0.90925613  0.45288827  0.59346925  0.44733684]]
[ 1.67859845  2.40295048]
[ 0.1257997   0.45288827  0.12380393  0.44733684]
[ 0.73621504  0.90925613]


In [2]:
import numpy as np
A = np.arange(2,14).reshape((2,6))
print(np.argmin(A))
print(np.argmax(A))#索引的最大值
print(np.mean(A))  
print(A.mean())    #平均值
print(np.median(A))#中位數
print(np.average(A))#平均值

print(A)
print(np.cumsum(A))#累加
print(np.diff(A))  #每一個的差
print(np.nonzero(A))#代表第0行第0列的數字是非零，以此類推

B=np.arange(13,1,-1).reshape((3,4))
print(B)
print(np.sort(B))#每一列排序

print(np.transpose(B))#行列互換
print(B.T)
print((B.T).dot(B))

print(B)
print(np.clip(B,5,9))#所有大於9的數，都變成9，所有小於5的數，都變成5

print(B)
print(np.mean(B,axis=0))#0就是對於每行做平均
print(np.mean(B,axis=1))#0就是對於每列做平均




0
11
7.5
7.5
7.5
7.5
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1 1 1]
 [1 1 1 1 1]]
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))
[[13 12 11 10]
 [ 9  8  7  6]
 [ 5  4  3  2]]
[[10 11 12 13]
 [ 6  7  8  9]
 [ 2  3  4  5]]
[[13  9  5]
 [12  8  4]
 [11  7  3]
 [10  6  2]]
[[13  9  5]
 [12  8  4]
 [11  7  3]
 [10  6  2]]
[[275 248 221 194]
 [248 224 200 176]
 [221 200 179 158]
 [194 176 158 140]]
[[13 12 11 10]
 [ 9  8  7  6]
 [ 5  4  3  2]]
[[9 9 9 9]
 [9 8 7 6]
 [5 5 5 5]]
[[13 12 11 10]
 [ 9  8  7  6]
 [ 5  4  3  2]]
[ 9.  8.  7.  6.]
[ 11.5   7.5   3.5]


In [14]:
import numpy as np
A = np.arange(3,15)
print(A)
print(A[3]) #印第三個值

B = np.arange(3,15).reshape((3,4))
print(B)
print(B[2])
print(B[1][1]) #索引指定值
print(B[1,1])  #索引指定值
print(B[:,2])  #所以第三列所有數
print(B[1,0:2])#索引第二列從第一個數到第三個數



[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8
[ 5  9 13]
[7 8]


In [20]:
C = np.arange(3,15).reshape((3,4))
print(C)

for row in C:
    print(row)
                #因為numpy不能印出colume，所以
for row in C.T: #把矩陣轉至，然後就可以印出colume
    print(row)

print(C.flatten())

for item in C.flat:
    print(item)
    


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [33]:
#array合併
import numpy as np

A = np.array([1,1,1])
B = np.array([2,2,2])
C = np.vstack((A,B))#vertical stack
D = np.hstack((A,B))#horizontal stack
E = A[:,np.newaxis] #讓橫向陣列變成縱向陣列
F = B[:,np.newaxis]


print(np.vstack((E,F)))
print(C)
print(D)
print(A.shape,C.shape,D.shape)
print(E)



[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,) (2, 3) (6,)
[[1]
 [1]
 [1]]


In [40]:
#array合併
import numpy as np

A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
print(A)
C = np.concatenate((A,B,B,A),axis = 1)#axis=0縱向合併，axis=1橫向合併
print(C)

[[1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
